### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by smlombardi** [johndugan/vscode-contrast-theme#1]
Very nice! Easy to read. I had to override 2 things:
1. sidebar background was too light IMO, dropped it to 232323
2. "editor.wordHighlightStrongBackground" being bright magenta was too much. For find matches it's excellent, but for matching the selection everywhere in the page it was distracting.

**Comment by johndugan** [comment]
Thank you!

re #1, I normally keep the sidebar closed. So, when I have it open it's important to me that the visual differentiation be apparent. Cool to hear about your override. Great use case for vscode team making that a possibility.

re #2, agree. Suggestions here?

PS - it's been a hot minute since I've reviewed it. Sorry for the severely delayed response!
